### ISSUE TITLE
Review possible mkvirtualenv/six install issue on Mac El Capitan

### ISSUE THREAD

**Issue by ironfroggy** [caktus/developer-documentation#26]
https://github.com/pypa/pip/issues/3165

**Comment by daaray** [comment]
I ran into this tonight....had to use:

`sudo pip install virtualenvwrapper --upgrade --ignore-installed six`

Is this tenable for-now/long-term?

**Comment by dpoirier** [comment]
The recommendation from a PyPA member here https://github.com/pypa/pip/issues/3165#issuecomment-176971783 suggests not using Apple's Python to get around this kind of problem with the way Apple has Python installed.
