### ISSUE TITLE
consider using brew rather than pythonz to install python 2.7 & 3.4 on macs

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/developer-documentation#9]
- pythonz doesn't put "python2.7", "python3.4" etc. executables on your PATH so you need to use $(pythonz locate 3.4.3) (https://github.com/saghul/pythonz/issues/11)
- tox allows overriding basepython, but this is complicated when the project also needs to run on Ubuntu (pretty much all the time), since there's no global config file for tox which would allow setting this 
- it's possible to install Python 2.7 and 3.4 with brew, which are the main two versions needed anyways (http://apple.stackexchange.com/questions/138931/what-is-the-correct-way-to-install-python-on-os-x)
- pythonz could still be documented as a way of getting other non-standard python versions on a mac

**Comment by ironfroggy** [comment]
The reason I was promoting pythonz over brew for Python is it doesn't seem
to offer much control other than "2 and 3" so, for Python 3, it doesn't
have a clear way to keep anything other than the latest release. The
homebrew python3 recipe has already been updated to 3.5 and we could have
projects in one machine that need 3.3, 3.4, and 3.5 at the same time.

Pythonz is a good parallel to the desdsnakes PPA.

**Comment by tobiasmcnulty** [comment]
Have you found a good way to make tox / other utils find your Pythons
without a "forest of symlinks" as @brandon-rhodes called it (and without
breaking tox.ini for non-mac users)?


On Sun, Oct 11, 2015 at 11:25 AM, ironfroggy <notifications@github.com>
wrote:

> The reason I was promoting pythonz over brew for Python is it doesn't seem
> to offer much control other than "2 and 3" so, for Python 3, it doesn't
> have a clear way to keep anything other than the latest release. The
> homebrew python3 recipe has already been updated to 3.5 and we could have
> projects in one machine that need 3.3, 3.4, and 3.5 at the same time.
>
> Pythonz is a good parallel to the desdsnakes PPA.
> On Oct 11, 2015 9:43 AM, "Tobias McNulty" <notifications@github.com>
> wrote:
>
> >
> > - pythonz doesn't put "python2.7", "python3.4" etc. executables on
> > your PATH so you need to use $(pythonz locate 3.4.3) (saghul/pythonz#11
> > <https://github.com/saghul/pythonz/issues/11>)
> > - tox allows overriding basepython, but this is complicated when the
> > project also needs to run on Ubuntu (pretty much all the time), since
> > there's no global config file for tox which would allow setting this
> > - it's possible to install Python 2.7 and 3.4 with brew, which are the
> > main two versions needed anyways (pythonz could still be documented as a
> > way of getting other non-standard python versions on a mac)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/caktus/developer-documentation/issues/9>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caktus/developer-documentation/issues/9#issuecomment-147211144>
> .
>



-- 


*Tobias McNulty*Chief Executive Officer

tobias@caktusgroup.com
www.caktusgroup.com

**Comment by ironfroggy** [comment]
I added symlinks inside the project virtualenv for which I was running tox.
It's an okay solution. It is definitely something that deserves to be
documented and improved.

**Comment by brandon-rhodes** [comment]
Random data point: I have had very good luck having students and friends install Python on OS X via Anaconda — `conda create python=3.4` and so forth. Both 2.7 and 3.4 are supported, not just the most recent version of each series: https://www.continuum.io/downloads
